### PR TITLE
Fix #293 SlackApiException and other exceptions are not standard

### LINKED ISSUE #293: SlackApiException and other exceptions are not standard
SlackApiException does not set Throwable.detailMessage, so when you catch the exception and try to log it, the message is "null".

Since you cannot set the message by calling `Exception(String message)` would it be possible to overwrite Throwable::getMessage() to produce a readable message when logging?

### PR DESCRIPTION
**Pull request by seratch**
This pull request improves the issue pointed out by #293.

@kushal256 Could you leave comments if you see something to improve more?

### CODE REVIEW

File: jslack-api-client/src/main/java/com/github/seratch/jslack/api/methods/SlackApiException.java [hunk 1]
```diff
@@ -19,8 +19,26 @@ public SlackApiException(Response response, String responseBody) {
...
+        super(buildErrorMessage(response, error));
         this.response = response;
         this.responseBody = responseBody;
+        this.error = error;
+    }
+
+    private static String buildErrorMessage(Response response, SlackApiErrorResponse error) {
+        String message = "status: " + response.code();
+        if (error != null) {
+            return message + ", error: " + error.getError() + ", needed: " + error.getNeeded() + ", warning: " + error.getProvided() + ", warning: " + error.getWarning();
```
Comment (kushal256) [inline jslack-api-client/src/main/java/com/github/seratch/jslack/api/methods/SlackApiException.java]: This has the text `warning` twice, i think first one should be `provided`?

Would it be easier to just make this line instead `return message + error.toString()` as SlackApiErrorResponse already has toString() implemented from the lombok `@Data` annotation?

Comment (seratch) [reply jslack-api-client/src/main/java/com/github/seratch/jslack/api/methods/SlackApiException.java]: Good catch, thanks! >warning

>Would it be easier to just make this line instead return message + error.toString() as SlackApiErrorResponse already has toString() implemented from the lombok @Data annotation?

True, it would be much easier but I don't think it's good as the string would be much longer and it would be like "SlackApiErrorResponse(....)".

I don't think it's a good way
